---
- name: install | repo

  include_role: 
    name: community.mongodb.mongodb_repository
  vars:
       mongodb_version: "{{ mongo_version | regex_replace('\\d+(?:\\.\\d+)')  }}"
  when: mongo_repo
- name: install | install
  include_role: 
    name: community.mongodb.mongodb_install
  vars:
       specific_mongodb_version: "{{ mongo_version }}"

- name: install | config
  include_role: 
    name: community.mongodb.mongodb_config
  vars:
       bind_ip: "{{mongo_net.bindIp}}"
       config_port: "{{mongo_net.port}}"
       log_path: "{{mongo_systemlog.path}}"
       db_path: "{{mongo_storage.dbPath}}"
       skip_restart: not {{mongo_restart_config}}
       authorization: "{{mongo_security.authorization}}"
- block:

    - name: install | ensure log folder exists
      file:
        path: "{{ mongo_systemlog.path | dirname }}"
        state: directory
        owner: mongod
        group: mongod
        mode: '0775'

    - name: install | stat if log file exist
      stat:
        path: "{{ mongo_systemlog.path }}"
      register: mongo_log_check

    - name: install | ensure log files exist
      copy:
        content: ""
        dest: "{{ mongo_systemlog.path }}"
        force: true
        group: mongod
        owner: mongod
        mode: '0755'
      when: not mongo_log_check.stat.exists

  when: >-
    '/var/log/mongodb' not in mongo_systemlog.path and
    mongo_systemlog.destination == 'file'

- name: install | pymongo {{ mongo_pymongo_version }}
  pip:
    name: pymongo
    executable: pip3
    version: "{{ mongo_pymongo_version }}"
